version: '3'

services:
    db:
        image: mongo:latest
        volumes:
            - dbdata:/data/db
        ports:
            - ${MONGO_PORT:-27017}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}

volumes:
    dbdata:
