name: CI

on:
    pull_request:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    onlyforms:
        name: Onlyforms
        runs-on: ubuntu-latest
        container: node:20
        timeout-minutes: 30
        services:
            db:
                image: mongo:latest
                volumes:
                    - dbdata:/data/db
                ports:
                    - 27017:27017
                env:
                    MONGO_INITDB_ROOT_USERNAME: admin
                    MONGO_INITDB_ROOT_PASSWORD: password
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                id: pnpm-install
                with:
                    version: latest
                    run_install: false

            -   name: Install dependencies
                run: pnpm install

            -   name: Build
                run: pnpm build

            -   name: Test
                run: pnpm test
                env:
                    MONGO_USERNAME: admin
                    MONGO_PASSWORD: password
                    MONGO_HOST: localhost
                    MONGO_PORT: 27017
                    MONGO_DB: onlyforms